services:
#  postgresql:
#    container_name: postgresql
#    image: postgres
#    environment:
#      POSTGRES_USER: alibou
#      POSTGRES_PASSWORD: alibou
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped


  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Rootroot@1045
      MYSQL_DATA_DIR: /data/mysql
    volumes:
      - mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped



#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped


#  mysqladmin:
#    container_name: mysqladmin
#    image: mysql
#    environment:
#      MYSQLADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-mysql@mysqladmin.org}
#      MYSQLADMIN_DEFAULT_PASSWORD: ${MYSQLADMIN_DEFAULT_PASSWORD:-Rootroot@1045}
#      MYSQLADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - mysqladmin:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    networks:
#      - mysql
#    restart: unless-stopped



  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  mysql:
    driver: bridge
  zipkin:
    driver: bridge

#volumes:
#  postgres:
#  pgadmin:

volumes:
  mysql:
#  mysqladmin: